.TH Darling
.PP
Darling is a personnal programming assisant.
.SH Installation
.PP
TODO: Write installation instructions here
.SH Usage
.PP
TODO: Write usage instructions here
.SH Development
.PP
TODO: Write development instructions here
.SH Contributing
.nr step0 0 1
.RS
.IP \n+[step0]
Fork it ( \[la]https://github.com/Nephos/Darling/fork\[ra] )
.IP \n+[step0]
Create your feature branch (git checkout \-b my\-new\-feature)
.IP \n+[step0]
Commit your changes (git commit \-am 'Add some feature')
.IP \n+[step0]
Push to the branch (git push origin my\-new\-feature)
.IP \n+[step0]
Create a new Pull Request
.RE
.SH Contributors
.RS
.IP \(bu 2
Nephos \[la]https://github.com/Nephos\[ra] Arthur Poulet \- creator, maintainer
.RE
